enum SpecialFeatureMode {
  disabled,                     // 0
  minis,                        // 1
  modul0,                       // 2
  schnupperModul,               // 3
  basic_3x3,                    // 4
  seepferdchenFerienPfingsten,  // 5
  seepferdchenFerienSommer,     // 6
  betterSwim,                   // 7
  betterSwim2,                  // 8
  summerClass,                  // 9
  privatkursKind,               // 10
  privatkursErwachsen,          // 11
  privatkursKind2,              // 12
  privatkursErwachsen2,         // 13
  freundes3Kurs,                // 14
  freundes3Kurs2,               // 15
  elternKindKurs,               // 16
  elternLehrenSwim,             // 17
}
